### ISSUE TITLE
Some text is hidden in the introduction

### ISSUE THREAD

**Issue by gkaklas** [raatmarien/chibe#11]
When opening the app for the first time, some of the text in the introduction screens is hidden by the bottom bar.

**Comment by raatmarien** [comment]
I've shortened some parts of the intro in [v1.2.0](https://github.com/raatmarien/chibe/releases), which hopefully solves this. Let me know if this is still a problem in v1.2.0.

**Comment by gkaklas** [comment]
I just installed v1.2.0 and the problem still exists, at the second screen. Shortening the text doesn't work on all screens, e.g. < 5" (mine is 5"). Is there a way for the screens to scroll, or scale according to the screen size?

**Comment by raatmarien** [comment]
Thanks for letting me know! I'm using a library for the intro, so I'm not sure exactly how much is possible, but I'll look into it.

**Comment by smichel17** [comment]
Appintro v4.0 is released; you could try upgrading.

**Comment by raatmarien** [comment]
Thanks for letting me know @smichel17. I've updated the AppIntro version in v1.2.1 to v4.1.0. The AppIntro changelog says they fixed this issue and all the text displays nicely on an emulator with a small screen for me now. So it should be fixed now, feel free to reopen this issue if the problem still occurs on v1.2.1, thanks!
