### ISSUE TITLE
Enable sleep mode based on Android's Do Not Disturb

### ISSUE THREAD

**Issue by gkaklas** [raatmarien/chibe#12]
It would be nice if chibe had an option to detect the device's Do Not Disturb status for silencing itself. This has the advantage that it can follow my schedule even if I don't sleep at exactly the time I have set, since I can set DND before I go to sleep (and even automatically disable it when my alarm goes off).

**Comment by raatmarien** [comment]
Thanks for the suggestion, this is a nice addition to Chibe. I've released [v1.2.0](https://github.com/raatmarien/chibe/releases), which allows an option to disable the vibrations during Do Not Disturb on Android versions which support it. It should be up on F-Droid in a few days. Let me know if you have any feedback on the implementation :+1: .

**Comment by gkaklas** [comment]
I haven't noticed any problems so far, thanks for implementing this!
