### ISSUE TITLE
Not working with screen turned off

### ISSUE THREAD

**Issue by Tony-il-Capo** [raatmarien/chibe#13]
Hi there
I've tried Chibe (latest version from F-Droid) on my Sony Xperia S running stock android (4.1.2), it stops working after turning off the screen, making it kinda useless. When I turn on the screen again/unlock the device, it vibrates using the pattern I chose before on settings, no matter what time it is.
Power saving options ("extended standby") are turned off.

**Comment by raatmarien** [comment]
I am unable to replicate this on any of my devices. Could you try disabling battery optimization for Chibe if that is possible on your operating system?

**Comment by Tony-il-Capo** [comment]
Not possible, only that "extended standby" option is available.

I always have a few 'essential' apps running on background and they never stop doing their job with the screen off, but Chibe seems to stop working after screen off/lock, when I turn the screen on it starts working again. Similar 'alarm clock' apps always work...

e.g. Set Chibe hourly (i.e. next should be 5 PM) then alarm app to 5:05PM, Chibe fails, alarm app works.

Maybe you missed something to wake up the device?

Anyway, I gonna retest this tomorrow, well today, later!

**Comment by raatmarien** [comment]
I've released v1.2.1, which should be on F-Droid in a few days. It has a few fixes related to this, so could you let me know if it still occurs when you have updated? If so, feel free to reopen this issue.

**Comment by Tony-il-Capo** [comment]
OK, I will let you know.

**Comment by raatmarien** [comment]
Thanks :+1:

**Comment by Tony-il-Capo** [comment]
Hi
After some tests with the new version, I can say it works ok now. Device vibrates on time even with the screen turned off.

Many thanks.
