### ISSUE TITLE
custom startpoint with fix intervals

### ISSUE THREAD

**Issue by biiiep** [raatmarien/chibe#17]
hey,

really neat app. I was wondering if it would be possible to add another feature to remind of passing time in specific situations with custom startpoints i.e. during meetings.

- set an interval, i.e. 15min
- start the interval timer
- get reminded every 15min minutes

what do you think?

**Comment by raatmarien** [comment]
Hey, I'm happy you like Chibe!

Thanks for the feedback, I understand where you are coming from and how this would be useful. Unfortunately, I think it is better if Chibe focusses on being a general clock for now, like a cuckoo's clock, but with vibrations :). This keeps it easy to understand what Chibe is and keeps the app focussed. However, maybe someone could make a separate app that has this feature.

If you have any other ideas or comments, please let me know!
